version: '3'

services:

  db:
    image: mariadb:10.0
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=spark
    - MYSQL_USER=spark
    - MYSQL_PASSWORD=spark
    volumes:
    - "mysql:/var/lib/mysql"
    ports:
    - "3306:3306"

  camps_index:
    depends_on:
    - db
    build: .
    image: midburn-camps-index
    environment:
    - LOOP_INTERVAL_SECONDS=5
    - MYSQL_HOST=db
    - MYSQL_USER=spark
    - MYSQL_PASS=123456
    - MYSQL_PORT=3306
    - MYSQL_DB=spark
    volumes:
    - nginx_html:/usr/share/nginx/html

  nginx:
    ports:
    - "8080:80"
    depends_on:
    - camps_index
    image: nginx
    entrypoint:
    - bash
    - "-c"
    - |
      echo "
      server {
          listen       80;
          server_name  localhost;
          location / {
              root   /usr/share/nginx/html/public;
              index  index.html;
          }
          error_page 404 /404.html;
      }
      " > /etc/nginx/conf.d/default.conf
      nginx -g "daemon off;"
    volumes:
    - nginx_html:/usr/share/nginx/html



volumes:
  mysql:
  nginx_html:
